FROM centos:8

RUN yum upgrade -y &&\
	yum install -y epel-release &&\
	yum install -y tmux bind-utils net-tools nmap-ncat unzip vim iftop iotop psmisc telnet htop zip gawk figlet rsync nmap ncdu lsof curl &&\
	yum clean -y all
